//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_ID { get; set; }
        public string Pickup_Date { get; set; }
        public string Drop_Date { get; set; }
        public Nullable<int> Pickup_Location { get; set; }
        public Nullable<int> Drop_Location { get; set; }
        public string Booking_Status { get; set; }
        public Nullable<int> Discount_ID { get; set; }
        public string Registration_Number { get; set; }
        public Nullable<int> Member_ID { get; set; }
    }
}
