//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public string Registration_Number { get; set; }
        public string Car_Color { get; set; }
        public string Car_Brand { get; set; }
        public Nullable<int> Car_Company { get; set; }
        public string Location_ID { get; set; }
        public string Car_Seats { get; set; }
        public string Car_DailyPrice { get; set; }
        public string Car_Picture { get; set; }
    }
}
